services:
  db:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default_network
  backend:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    container_name: backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - '${BACKEND_APP_PORT}:${BACKEND_APP_PORT}'
    networks:
      - default_network
networks:
  default_network:
    name: store_network

volumes:
  postgres-data:
