services:
  db:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - '.env'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - '3001:3001'

  frontend:
    depends_on:
      - db
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - '.env'
    container_name: frontend
    ports:
      - '3000:3000'

volumes:
  postgres-data:
